/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TTableIdIndexRouteImport } from './routes/t.$tableId.index'
import { Route as TTableIdHostRouteImport } from './routes/t.$tableId.host'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TTableIdIndexRoute = TTableIdIndexRouteImport.update({
  id: '/t/$tableId/',
  path: '/t/$tableId/',
  getParentRoute: () => rootRouteImport,
} as any)
const TTableIdHostRoute = TTableIdHostRouteImport.update({
  id: '/t/$tableId/host',
  path: '/t/$tableId/host',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/t/$tableId/host': typeof TTableIdHostRoute
  '/t/$tableId/': typeof TTableIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/t/$tableId/host': typeof TTableIdHostRoute
  '/t/$tableId': typeof TTableIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/t/$tableId/host': typeof TTableIdHostRoute
  '/t/$tableId/': typeof TTableIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/t/$tableId/host' | '/t/$tableId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/t/$tableId/host' | '/t/$tableId'
  id: '__root__' | '/' | '/t/$tableId/host' | '/t/$tableId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TTableIdHostRoute: typeof TTableIdHostRoute
  TTableIdIndexRoute: typeof TTableIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$tableId/': {
      id: '/t/$tableId/'
      path: '/t/$tableId'
      fullPath: '/t/$tableId/'
      preLoaderRoute: typeof TTableIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$tableId/host': {
      id: '/t/$tableId/host'
      path: '/t/$tableId/host'
      fullPath: '/t/$tableId/host'
      preLoaderRoute: typeof TTableIdHostRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TTableIdHostRoute: TTableIdHostRoute,
  TTableIdIndexRoute: TTableIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
