// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nxmkgmqvgwkrimkqdeiv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im54bWtnbXF2Z3drcmlta3FkZWl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODg0MzUxOTAsImV4cCI6MjEwNDAxMTE5MH0.a2Sy6cgQ43PLjAcJA5mtYXitk7bUHLmyH7QSopcB5KM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});